version: '3.9'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: practicas_tesis_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kali123
      POSTGRES_DB: practicas_tesis_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend NestJS
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: practicas_tesis_backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:kali123@postgres:5432/practicas_tesis_db?schema=public
      JWT_SECRET: super_secret_jwt_key_practicas_tesis_unt_2024
      JWT_EXPIRES_IN: 7d
      PORT: 3001
      NODE_ENV: production
      FRONTEND_URL: http://localhost:3000
    ports:
      - '3001:3001'
    networks:
      - app_network
    command: sh -c "npx prisma migrate deploy && node dist/main"

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: practicas_tesis_frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/api/v1
    ports:
      - '3000:3000'
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
